# ===============================
# = Spring configurations
# ===============================
spring:
  name: local
  # = HTTP requests configurations ##############################
  servlet:
    multipart:
      location: /tmp
  datasource:
    url:      ${env.SPRING_DATASOURCE_URL}
    username: postgres # ${env.SPRING_DATASOURCE_USERNAME}
    password: 1234 # ${env.SPRING_DATASOURCE_PASSWORD}
